### ISSUE TITLE
Página en blanco al intentar activar Latch del lado del usuario

### ISSUE THREAD

**Issue by felihommen** [ElevenPaths/latch-plugin-prestashop#8]
En una instalación reciente de Prestashop 1.6.1.1 he instalado el módulo de Latch. Cuando como usuario, dentro de mi cuenta, hago click en "Proteja su cuenta con Latch" obtengo una página en blanco y el siguiente error en el registro de apache:
```
PHP Fatal error:  Class 'LatchPSLatchConfModuleFrontController' not found in /var/www/html/classes/controller/Controller.php on line 134, referer: https://www.ejemplo.com/es/mi-cuenta
```

**Comment by jaesga** [comment]
Hola, 

Vamos a escalar esta incidencia para tratar de averiguar si el plugin a dejado de ser compatible con la ultima version de Prestashop y tratar de solucionarlo.

Muchas gracias por el aviso. 
Javier.

**Comment by jaesga** [comment]
Hola de nuevo,
Nuestro departamento de pruebas ha probado el plugin de latch existente en la rama master en una instalación limpia de 1.6.1.1 y no ha sido capaz de reproducir el error que nos comentas.

Puedes confirmarnos que no se trata de un problema de permisos y que tienes instalada la extension curl de PHP? Que version de PHP utilizas?

Para poder ayudarte mejor y tener un seguimiento de esta incidencia si quieres puedes escribir a nuestra dirección de soporte: 
Latch-help@support.elevenpaths.com

Un saludo,
Javier
